### ISSUE TITLE
Problème de détection d'id_quest non alphanumérique

### ISSUE THREAD

**Issue by JMPivette** [JMPivette/evavelo#42]
Problème avec les id_quest… J’ai oublié de t’en parler ce matin. Il semble que l’appli ne considèrent comme conforme que les id alphanumériques. Or le modèle d’id définit par la méthode est xxxx (questionnaire simple et ou xxx est un numéro ex 106) ou xxx-xx (pour les questionnaires multiples qui ajoute un suffixe au numéro principal ex : pour un questionnaire qui aurait dû être le 106, cela donne 106-1, 106-2, 106-3).

Si c’est une vraie nécessitée d’être en alphanumérique dis-le moi car il va falloir adapter le guide et le catalogue des variables.

**Comment by JMPivette** [comment]
@VeloTerritoire 
Est-ce que tu as un exemple de fichier qui pose le problème?

A priori il n'y a pas de problème au niveau des caractères dans id_quest et on peut mettre ce qu'on veut.

Par contre au niveau des questionnaires multiples, Eva-scan s'attend à des id_quest avec ce format:
* dans `comptage`: XXXX (n'importe quel type de caractère et n'importe quelle longueur)
* dans `enquete`: XXXX-YYY (YYY étant numérique et de n'importe quelle longueur).

Par exemple,
`106` dans comptage et `106-1` , `106-2` dans enquête

Ou même 
`12$-SF` dans comptage et `12$-SF-998` , `12$-SF-954` dans enquête

Par contre ce qui ne marchera pas, c'est:
`106-01`dans comptage et `106-01`dans enquête. 
En effet Eva-scan va enlever le suffixe dans enquête pour rechercher l'id_quest `106`dans comptage.

**Comment by VeloTerritoires** [comment]
@JMPivette 
Je ne l'ai pas sauvegardé. Mais je peux te le refaire. J'essaie de le faire là (mais je suis en réunion ;-) alors si ça ne viens pas vite, ne t'inquiète pas).

**Comment by VeloTerritoires** [comment]
@JMPivette 
grrr, je viens d'essayer avec du tout numérique et pas de souci cette fois :-p

J'avais eu ce message et remis une lettre partout et cela avait fonctionné 

![image](https://user-images.githubusercontent.com/76215024/108365505-95dbc180-71f7-11eb-83df-2a4b3e58008b.png)

**Comment by JMPivette** [comment]
Super d'avoir gardé le message d'erreur! Du coup je pense savoir d'où vient l'erreur.

Si dans le fichier xlsx, la colonne `id_quest` est numérique, mon process d'import va garder ce format numérique..
Je vais forcer la lecture en chaîne de caractères lors de l'import du fichier xlsx.
