### ISSUE TITLE
Probleme d'affectation de catégorie cas 5

### ISSUE THREAD

**Issue by JMPivette** [JMPivette/evavelo#48]
![image](https://user-images.githubusercontent.com/46813298/108519838-516d2600-72ca-11eb-9ed5-4397c320a495.png)

**Comment by JMPivette** [comment]
@VeloTerritoires

* A4, A8 et A12: ok le problème vient d'une non-gestion des valeurs manquantes sur la distance. En cas de non-réponse , je ne trancherai pas.

* A5 A6: Si je n'ai pas de réponse sur le type de trajet, je tranche à partir seulement de la distance?

* A9 A10: Si je reprend la méthodologie, on est pour moi dans le cas "sportif" (pas d'aller-retour):
>
![image](https://user-images.githubusercontent.com/46813298/108520515-0f90af80-72cb-11eb-98a7-acf326a11b8e.png)

**Comment by VeloTerritoires** [comment]
Ok pour tout
