### ISSUE TITLE
Probleme d'affectation de catégorie cas 6 &11

### ISSUE THREAD

**Issue by JMPivette** [JMPivette/evavelo#49]
Cas Sportif / Loisir et Loisir / Sportif

Cas 6:
![image](https://user-images.githubusercontent.com/46813298/108520945-829a2600-72cb-11eb-85ef-3ddec78d5b53.png)

Cas 11:
![image](https://user-images.githubusercontent.com/46813298/108845971-5a1d6f00-75de-11eb-91dd-04b05cd915fe.png)

**Comment by JMPivette** [comment]
@VeloTerritoires
Pour les cas 6 et 11 , les cas qui ne permettent pas de trancher sont:

- pas de réponses type de vélo + pas de réponses km
- pas de réponses vae + km > 50km

Est-ce que cela te convient?

**Comment by VeloTerritoires** [comment]
@JMPivette 
Pour les cas 6 et 11 , les cas qui ne permettent pas de trancher sont:

pas de réponses type de vélo + pas de réponses km
pas de réponses type de vélo + km > 50km
Est-ce que cela te convient?

C'est pas super clair sur le guide... Je me note de reprendre cela.

**pas de réponses type de vélo + pas de réponses km**
>> oui , on va dire que l'on ne peut pas trancher

**pas de réponses type de vélo + km > 50km**
>> je pense que si pas de réponse au type de vélo + km> 50 quand réponse aux activités alors on peut trancher. (Si autre activité = loisir, si pas d'activité = sportif). Par contre, s'il n'y a pas de réponse à la question sur les activités, on ne peut pas trancher.

**Comment by VeloTerritoires** [comment]
@JMPivette 
Pour le cas 11 / A32 - A35 - A40:
Selon la méthodologie, on doit trancher en loisir:
image

Ou alors si "pas de vae" et pas de réponse km, il ne faut pas trancher?

Ce serait plus juste avec ta proposition si pas de vae + pas de km, on ne tranche pas.
Je pense que j'ai du oublié d'imbriquer quelque chose dans le texte... Sinon tous les cas ne sont pas traités...

**Comment by JMPivette** [comment]
Je suis en train de relire les cas 6 et 11.
Pour simplifier: à partir du moment ou le vélo est un VAE, on va classifier en "Loisir" et non "Sportif" peu importe les réponses ou non-réponses aux autres questions?

**Comment by VeloTerritoires** [comment]
@JMPivette 
Oui dès que c'est du VAE, c'est du loisir.
