### ISSUE TITLE
Onglets indispensables pour la lecture du fichier et blocage en cas d'onglets vides

### ISSUE THREAD

**Issue by JMPivette** [JMPivette/evavelo#77]
Dans la documentation, il est écrit que pour pouvoir être lu le fichier doit comporter au moins les 6 onglets suivants et que l’absence de l’un de ses onglets entraînera une erreur avec les fonctions read et process:

- calendrier_sites
- table_communes
- comptages_manuels
- comptages_man_post_traitements
- enquetes_saisies
- enquetes_post_traitement

En fait, je viens de tester et la réalité porte plutôt sur 7 onglets et le 7ème ne produit pas les mêmes effets que les autres (**comptages_automatiques**). Voici les cas que j’ai testé et les résultats :

Onglets | Feuille sans données mais avec les en-têtes | Feuille vide | Feuille absente
-- | -- | -- | --
table_communes | RAS | bloquant | bloquant
calendrier_sites | RAS | bloquant | bloquant
comptages_manuels | RAS | bloquant | bloquant
comptages_manuels_post_traitements | RAS | bloquant | bloquant
enquêtes_saisies | RAS | bloquant | bloquant
enquêtes_post_traitement | RAS | bloquant | bloquant
comptages_automatiques | bloquant | Warning d’absence de données | bloquant

J’aurai plutôt imaginé les effets suivants :

Onglets | Feuille sans données mais avec les en-têtes | Feuille vide | Feuille absente
-- | -- | -- | --
table_communes | bloquant | bloquant | bloquant
calendrier_sites | bloquant | bloquant | bloquant
comptages_manuels | bloquant | bloquant | bloquant
comptages_manuels_post_traitements | bloquant | bloquant | bloquant
enquêtes_saisies | bloquant | bloquant | bloquant
enquêtes_post_traitement | bloquant | bloquant | bloquant
comptages_automatiques | Warning d’absence de données | Warning d’absence de données | bloquant

**Comment by VeloTerritoires** [comment]
@JMPivette est-ce normal que je ne vois rien de changé dans la documentation, ni dans le fonctionnement d'EVA-Scan ?

**Comment by JMPivette** [comment]
@VeloTerritoires Oui c'est normal, Rien n'a changé sur la version de production.
Tous les changements que j'ai effectué hier sont sur une branche de développement. Je devrais pouvoir faire une release aujourd'hui (si tous les tests unitaires passent bien)

**Comment by VeloTerritoires** [comment]
ok merci
