### ISSUE TITLE
Vérification de la liste des catégories dans comptages_man_post_traitement (variantes au pluriel)

### ISSUE THREAD

**Issue by VeloTerritoires** [JMPivette/evavelo#79]
@JMPivette  Dans le code, on voit que normalement seules les catégories : `loisir`, `sportif`, `itinérant`, `utilitaire`sont censées être acceptées et ne pas donner lieu à une anomalie dans le log.

> # Check values of categorie_visuelle_cycliste
  wrong_cat <- dplyr::setdiff(unique(eva_data$comptage$categorie_visuelle_cycliste),
          c("Loisir","Sportif","Utilitaire","Itin\u00e9rant", NA))
  if (length(wrong_cat) != 0 ) {
    err <- TRUE
    log <- add_message_log(
      log,
      " ERREUR: pr\u00e9sence de valeurs non-standard dans \'categorie_visuelle_cycliste\': ",
      paste(wrong_cat, collapse = ", ")
    )
  }

Pourtant, avec `loisir`, comme `loisirs` ça passe sans anomalie alors que `sportifs`, `utilitaires`, `itinérants` sont signalés comme une anomalies
> Vérification de comptages_man_post_traitements...
 ERREUR: présence de valeurs non-standard dans 'categorie_visuelle_cycliste':  Sportifs, Utilitaires, Itinérants

Je n'arrive pas à comprendre pourquoi. Tu as une idée ?

**Comment by JMPivette** [comment]
Oui, je vois d'où cela vient:
Lors de la lecture du fichier, je fais une modification de `loisirs` en `loisir` parce que l'erreur apparaissait dans mon fichier d'input valide.

https://github.com/JMPivette/evavelo/blob/2006d70734e6bf83d2a48f57fc8cf548e22bebcf/R/read_evavelo.R#L70

Je peux enlever cette vérification ou même supprimer les "s" au moment de la lecture de l'onglet comptage.

**Comment by VeloTerritoires** [comment]
@JMPivette, oui c'était une erreur de saisie que j'avais oublié de corriger avant de t'envoyer le fichier. Mais la norme c'est bien "Loisir" sans s. Je te laisse me faire la proposition la plus adéquate.

**Comment by JMPivette** [comment]
Je vais supprimer les "s" en fin de catégorie automatiquement et mettre à jour la documentation

**Comment by VeloTerritoires** [comment]
oki
